version: "3.6"

# Using Docker_BuildKit which requires:
# export DOCKER_BUILDKIT=1
# export COMPOSE_DOCKER_CLI_BUILD=1

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8

services:

  api:
    restart: always
    # build: ../api
    image: ghcr.io/hssrobotics23/api/dgmd_apis:latest
    container_name: dgmd_api
    environment:
      - MLFLOW_TRACKING_URI=http://dgmd_mlflow:5000/
      - MODEL_NAME=dgmd_model
      - AWS_SHARED_CREDENTIALS_FILE=/secrets/aws_credentials    
    expose:
      - "8080"
    ports:
      - "80:8080"
    volumes:
      - secret-vol:/secrets
      - "../api:/app"
    networks:
      - frontend
      - backend
  
  mlflow:
    restart: always
    # build: ../mlflow
    image: ghcr.io/hssrobotics23/mlflow/dgmd_mlflow:latest
    container_name: dgmd_mlflow
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/secrets/aws_credentials
    volumes:
      - db-vol:/db
      - secret-vol:/secrets
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - backend

  model-pipeline:
    # build: ../model_training_pipeline
    image: ghcr.io/hssrobotics23/model_training_pipeline/dgmd_model_pipeline:latest
    container_name: dgmd_model_pipeline
    volumes:
      - secret-vol:/secrets
      - ./data:/app/data
      - ../model_training_pipeline:/app
    environment:
      - MLFLOW_TRACKING_URI=http://dgmd_mlflow:5000/
      - MODEL_NAME=dgmd_model
      - AWS_SHARED_CREDENTIALS_FILE=/secrets/aws_credentials
    depends_on:
      - mlflow
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  secret-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/secrets
  db-vol: null
